version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: appointment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres